### ISSUE TITLE
Payment.get_subscription_details and Payment.get_service_details return more details

### ISSUE THREAD

**Issue by evangriffiths** [nevermined-io/payments-py#11]
## Is your feature request related to a problem? Please describe.

`Payment.get_subscription_details` and `Payment.get_service_details` currently just return the URL to inspect the subscription/service in the web UI.

## Describe the solution you'd like

Either they should be renamed (to e.g `get_subscription_url`), or preferably return some json containing the actual details (price, name, description, etc.).

**Comment by eruizgar91** [comment]
Hi @evangriffiths . Currently you can get the full ddo of a subscription/service/file using the getDDO method. Do you need something more specific? Cause there you can get the full metadata object. Thank you

**Comment by evangriffiths** [comment]
Ah great, that's [`get_asset_ddo`](https://nevermined-io.github.io/payments-py/payments.html#method-get_asset_ddo) in the python API 👍. Didn't know that's what it did. Please close this issue in that case (although IMO these `get_*_details` could do with being renamed to `get_*_url` - so could rename it to that 😄)
