### ISSUE TITLE
Get user's wallet address programatically

### ISSUE THREAD

**Issue by evangriffiths** [nevermined-io/payments-py#14]
## Is your feature request related to a problem? Please describe.

When getting my balance of a subscription, I need my `API_KEY` and `WALLET_ADDRESS`:
```
API_KEY = ...
WALLET_ADDRESS = ...
did = ...
Payments(nvm_api_key=API_KEY, environment=Environment.appTesting)
response = payments.get_subscription_balance(
    subscription_did=did,
    account_address=WALLET_ADDRESS,
)
```

Since there is only one wallet associated with the user, and the user is known based on the API key, can I either:

1. get the wallet address programatically, based on the API key 
2. or even better, not require the `account_address` arg on `Payments.get_subscription_balance` at all

?

**Comment by clriesco** [comment]
Fixed
